version:'1'
services:
	db:
		build: ./mariadb
		ports:
		- 3306:3306
		restart: unless-stopped
   		logging:
     		driver: "json-file"
     		options:
       			max-size: "3m"
       			max-file: "1"
	py:
		build: ./python
		depends_on:
		- db
		restart: unless-stopped
   		logging:
     		driver: "json-file"
     		options:
       			max-size: "3m"
       			max-file: "1"
	web:
		build: ./flask
		ports:
		- 5000:5000
		depends_on:
		- db
		restart: unless-stopped
   		logging:
     		driver: "json-file"
     		options:
       			max-size: "3m"
       			max-file: "1"
	ssl:
		build: ./nginx
		ports:
		- 80:80
		- 443:443
		depends_on:
		- db
		restart: unless-stopped
   		logging:
     		driver: "json-file"
     		options:
       			max-size: "3m"
       			max-file: "1"