FROM python:3.10.12
WORKDIR /python
COPY . /python/
RUN pip install requests \
	&& pip install pymysql \
	&& pip install beautifulsoup4 \
	&& pip install flask
EXPOSE 5000
ENV FLASK_RUN_HOST 127.0.0.1
CMD ["python3","test.py"]